baseURL = "https://www-haosp.org/"
languageCode = "es"
title = "Blog de Superación Personal"
theme = "PaperMod"
publishDir = "public"

[pagination]
  pagerSize = 10

[params]
  author = "Héctor Augusto Ospina Angarita"
  description = "Reflexiones sobre principios, autoconciencia, sexualidad humana y vida social."
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowWordCount = true
  ShowToc = true
  defaultTheme = "auto"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "principios"
    name = "Principios"
    url = "/categories/principios/"
    weight = 1

  [[menu.main]]
    identifier = "autoconocimiento"
    name = "Autoconocimiento"
    url = "/categories/autoconocimiento/"
    weight = 2

  [[menu.main]]
    identifier = "sexualidad"
    name = "Sexualidad Humana"
    url = "/categories/sexualidad/"
    weight = 3

  [[menu.main]]
    identifier = "ser-social"
    name = "Ser social"
    url = "/categories/ser-social/"
    weight = 4

  [[menu.main]]
    identifier = "acerca-de"
    name = "Acerca de"
    url = "/about/"
    weight = 5
